#yml 개행, 띄어쓰기 : 을 기준으로 계층을 구분
#예 server: 
#      port: -> server.port
server: 
  port: 9090

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: spring
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: false
      connection-test-query: select 1 from dual
      pool-name: bspool
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    
    
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#fileUpload 처리 설정하기
  servlet:
    multipart:
      max-file-size: 10MB
        


#mybatis 설정하기
#mybatis:
#  mapper-locations: classpath:/mappers/**/*.xml
#  config-location: classpath:/config/mybatis-config.xml
  
#log설정하기
logging:
  file: 
    name: logs/springboot.log
  level:
    '[com.bs.helloboot]': debug
    
linux:
  url: http://14.36.141.71
  port: 9994
  baseDir: /home/bsyoo
  


  
